#!/usr/bin/env python3
"""Token-reduction lever: gold bbox prompt vs a compact prompt, on real pages.

The gold pipeline uses HIGH_ACCURACY_BBOX_PROMPT, which makes the model emit a `data-bbox`
coordinate set for every div — tokens we pay for but don't use (we parse the voter table,
not bboxes). This measures, per page:

  - tokens generated by the bbox prompt vs a compact "OCR to HTML" prompt (thermal-independent
    speed proxy: decode time scales with tokens), and
  - whether the compact output still contains the same voter fields as the gold bbox output.

Both variants run in ONE batch (same server, interleaved) so thermal state is shared.

Usage:
  python bench/prompt_tokens.py PDF --pages 3-5 [--dpi 192] [--model models/surya-2-Q4_K_M.gguf --mmproj X]
"""

import argparse
import difflib
import os
import sys
import time

# import the voter-field extractor from the sibling harness
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from compare_quality import extract_voters, strip_tags  # noqa: E402

COMPACT_PROMPT = "OCR this image to HTML."

FIELDS = ["name", "rel_name", "house", "age", "sex"]


def parse_pages(spec, n):
    out = []
    for part in (spec or f"1-{n}").split(","):
        if "-" in part:
            a, b = part.split("-"); out += range(int(a) - 1, int(b))
        else:
            out.append(int(part) - 1)
    return [i for i in out if 0 <= i < n]


def field_match(gold_html, var_html):
    """Per-field exact-match counts of variant voters vs gold voters (keyed by serial)."""
    gv, vv = extract_voters(gold_html), extract_voters(var_html)
    hits = {f: [0, 0] for f in FIELDS}
    for k in set(gv) & set(vv):
        for f in FIELDS:
            a, b = gv[k][f].lower().strip(), vv[k][f].lower().strip()
            if a:
                hits[f][1] += 1
                hits[f][0] += (a == b)
    return hits, len(gv), len(vv)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("pdf")
    ap.add_argument("--pages", default="3-5")
    ap.add_argument("--dpi", type=int, default=192)
    ap.add_argument("--model", default=None)
    ap.add_argument("--mmproj", default=None)
    ap.add_argument("--max-tokens", type=int, default=12288)
    args = ap.parse_args()

    if args.model:
        os.environ["SURYA_GGUF_LOCAL_MODEL_PATH"] = args.model
    if args.mmproj:
        os.environ["SURYA_GGUF_LOCAL_MMPROJ_PATH"] = args.mmproj
    os.environ.setdefault("DISABLE_TQDM", "true")

    from pdf2image import convert_from_path
    from pdf2image.pdf2image import pdfinfo_from_path
    from surya.inference import SuryaInferenceManager
    from surya.inference.schema import BatchInputItem, PROMPT_TYPE_HIGH_ACCURACY_BBOX

    npages = int(pdfinfo_from_path(args.pdf)["Pages"])
    idx = parse_pages(args.pages, npages)
    # .convert("RGB") forces a full in-memory load (pdf2image's lazy temp-file
    # images otherwise truncate under concurrent scale_to_fit in the worker pool).
    images = [convert_from_path(args.pdf, dpi=args.dpi, first_page=i + 1, last_page=i + 1)[0]
              .convert("RGB") for i in idx]

    manager = SuryaInferenceManager()

    # build interleaved batch: per page, a bbox item and a compact item
    batch = []
    for i, img in zip(idx, images):
        batch.append(BatchInputItem(image=img, prompt_type=PROMPT_TYPE_HIGH_ACCURACY_BBOX,
                                    prompt=None, max_tokens=args.max_tokens,
                                    metadata={"page": i + 1, "variant": "bbox"}))
        batch.append(BatchInputItem(image=img, prompt_type=PROMPT_TYPE_HIGH_ACCURACY_BBOX,
                                    prompt=COMPACT_PROMPT, max_tokens=args.max_tokens,
                                    metadata={"page": i + 1, "variant": "compact"}))

    # warm (server start + Metal compile) on the first image, untimed
    manager.generate([BatchInputItem(image=images[0],
                                     prompt_type=PROMPT_TYPE_HIGH_ACCURACY_BBOX,
                                     prompt=COMPACT_PROMPT, max_tokens=256,
                                     metadata={})])

    # Run ONE request at a time. Concurrent dense pages thrash the M4 (throughput
    # splits under the thermal ceiling) and blow past the per-request timeout. The
    # primary metric (token_count) is thermal-independent, so sequential is fine.
    t = time.time()
    by = {}
    for item in batch:
        o = manager.generate([item])[0]
        by[(item.metadata["page"], item.metadata["variant"])] = o
    elapsed = time.time() - t

    print(f"\nmodel: {args.model or 'f16-default'}   pages: {[i+1 for i in idx]}   "
          f"batch wall: {elapsed:.1f}s\n")
    print(f"{'page':>4}  {'bbox_tok':>9} {'compact_tok':>12} {'reduction':>10}  "
          f"{'text_sim':>8}  field-match(compact vs gold)")
    tot_bbox = tot_comp = 0
    agg = {f: [0, 0] for f in FIELDS}
    for i in idx:
        b = by[(i + 1, "bbox")]; c = by[(i + 1, "compact")]
        tot_bbox += b.token_count; tot_comp += c.token_count
        red = b.token_count / max(c.token_count, 1)
        sim = difflib.SequenceMatcher(None, strip_tags(b.raw), strip_tags(c.raw)).ratio()
        hits, _, _ = field_match(b.raw, c.raw)
        for f in FIELDS:
            agg[f][0] += hits[f][0]; agg[f][1] += hits[f][1]
        fm = " ".join(f"{f[:4]}={hits[f][0]}/{hits[f][1]}" for f in FIELDS)
        print(f"{i+1:>4}  {b.token_count:>9} {c.token_count:>12} {red:>9.2f}x  "
              f"{sim*100:>7.1f}%  {fm}")

    print(f"\n  TOTAL tokens: bbox={tot_bbox}  compact={tot_comp}  "
          f"-> {tot_bbox/max(tot_comp,1):.2f}x fewer tokens with compact prompt")
    print(f"  field-match compact vs gold (over fields gold has):")
    for f in FIELDS:
        m, n = agg[f]
        print(f"    {f:<9} {m}/{n}  {100*m/n if n else 0:.1f}%")

    try:
        manager.stop()
    except Exception:
        pass


if __name__ == "__main__":
    sys.exit(main())
